### ISSUE TITLE
Anchor links?

### ISSUE THREAD

**Issue by jehoshua02** [WICG/cq-usecases#12]
Would it be easy or worth it to add anchor tags throughout [the document](http://responsiveimagescg.github.io/eq-usecases/) to link to individual paragraphs in issues and things?

**Comment by peterwilsoncc** [comment]
[tabatkins/bikeshed](https://github.com/tabatkins/bikeshed/) is used to generate the document, it automatically generates IDs for headings that can be referenced. Paragraphs do not have IDs - presume becuase they are likely to change/be reordered.

**Comment by jehoshua02** [comment]
Yeah, and I just realized it's in github. Could easily link to source code.

**Comment by marcoscaceres** [comment]
We usually link to definitions or concepts instead of sections or paragraphs. I would suggest closing this, as BS will automatically generate the appropriate anchor points.

**Comment by tabatkins** [comment]
Yeah, headings, definitions, issues, and a few other small things auto-generate IDs with Bikeshed, and get clickable permalinks. That's generally all you need.

(If, for example, there's a list that you want to make linkable, manually adding an ID to the `<li>` or `<dt>` will make Bikeshed generate clickable permalinks as well.)
