### ISSUE TITLE
Module layouts

### ISSUE THREAD

**Issue by Wilto** [WICG/cq-usecases#2]
So, we need a single-breakpoint module dealie that breaks in especially visible ways when dropped into an inappropriate context. Once we have these layouts sorted, I’ll replace the Layout A/B placeholders in the layout wireframes with these (see #1). I’m working on a couple of things for this, but if anyone wants to take a stab at it here’s the template:

![wireframe](https://cloud.githubusercontent.com/assets/439942/3091922/1368ba56-e5a3-11e3-932d-416d0f0f367a.gif)

**Comment by Wilto** [comment]
I’m working on this now, but it’s pretty much just text—it won’t look _ideal_ when shown at the wrong size, but all this text will reflow more or less okay.

![image](https://cloud.githubusercontent.com/assets/439942/3092035/9ed9243a-e5a4-11e3-87cc-6a05f6439e76.png)

What we really need is something that’s like “whoop, woah, that is _busted_” when Layout B is applied at Layout A sizes, and looks awkwardly spaced-out when Layout A is applied at Layout B sizes.

**Comment by BPScott** [comment]
I think the easiest way to create _woah, busted_ is to create another module-like thing within the current module to create a new eq context.

A potential way of doing this is placing an overlay above the image in your module whose size / content changes based on the size of the image. An example of this in the wild is the play icon / "days to watch" overlay on the [bbc.co.uk/programmes' programme object](http://www.bbc.co.uk/programmes/styleguide/programme-object).

An alternative is to display a number of modules in a list that is vertical at small sizes, but at larger sizes becomes a grid - in this case the column count is dependant upon viewport size, but the module depends on the width of the grid column.
