### ISSUE TITLE
JavaScript Polyfill

### ISSUE THREAD

**Issue by ChrisBAshton** [WICG/cq-usecases#29]
I came up with [Localised CSS](https://github.com/ChrisBAshton/localised-css) before I found out about the Element Query movement. Glad to hear that there's some progress on this!

In the meantime, Localised CSS could be used as a polyfill for Element Queries. [This blog post](http://ashton.codes/blog/localised-css/) justifies some of the design decisions for the API.

Any feedback would be appreciated.

**Comment by serapath** [comment]
I found those:
- https://github.com/KyleAMathews/element-resize-event
- https://github.com/marcj/css-element-queries

Maybe those help?

**Comment by eeeps** [comment]
Added these and others to a [new page on the wiki](https://github.com/WICG/cq-usecases/wiki/Speculative-Prolyfills); closing.
