### ISSUE TITLE
Require ability to use with <picture>?

### ISSUE THREAD

**Issue by eeeps** [WICG/cq-usecases#38]
Eventually, I want to be able to do something like:

```html
<picture>
  <source container="(width > 500px)" srcset="original.jpg" />
  <img src="cropped.jpg" />
</picture>
```

Dunno if it’s worth stating this use case in this document, or whether we should just figure out container-queries-in-CSS first, and then figure out how to plug them into HTML later.

**Comment by JamesAnunda** [comment]
I say let's figure out the Container-queries first before I start plugging in the HTML.

**Comment by ZeeCoder** [comment]
I concur, it seems like this'll be a bit harder to figure out too, since media="" can have the implicit target (viewport), while a container query will need to explicitly state what the query should be related to.

**Comment by eeeps** [comment]
@ZeeCoder You're right that this gets complicated without an implicit target. Implicit targets are a possibility (e.g., [cq-prollyfill](https://github.com/ausi/cq-prolyfill) has ’em), but I agree with both you and @JamesAnunda that they, and this use case, are not important enough to be a requirement.

Tabling this to revisit in the (possibly rather distant) future.
