### ISSUE TITLE
Informative References

### ISSUE THREAD

**Issue by Wilto** [WICG/cq-usecases#5]
Getting a list of articles on the subject going.
- http://filamentgroup.com/lab/element-query-workarounds.html
- http://www.jonathantneal.com/blog/thoughts-on-media-queries-for-elements/
- http://www.xanthir.com/b4PR0
- http://www.xanthir.com/b4VG0

Keep ’em coming.

**Comment by justincavery** [comment]
http://www.smashingmagazine.com/2013/06/25/media-queries-are-not-the-answer-element-query-polyfill/

http://css-tricks.com/thoughts-media-queries-elements/

**Comment by derekjohnson** [comment]
http://hugogiraudel.com/2014/04/22/why-element-queries-matter/

**Comment by Wilto** [comment]
http://fremycompany.com/BG/2013/Element-Media-Queries-min-width-883/
http://discourse.specifiction.org/t/element-queries/26/8

**Comment by Wilto** [comment]
http://www.backalleycoder.com/2014/04/18/element-queries-from-the-feet-up/

**Comment by hereinthehive** [comment]
I'm stockpiling these myself here: https://kippt.com/hereinthehive/element-query-resources. Short of time this second but will feed back with any specifics that are worth a read.

**Comment by jehoshua02** [comment]
I thought I was the only one thinking about these things when I wrote [breakpoints.js](https://github.com/reusables/breakpoints.js). There is a [demo page](http://reusables.io/breakpoints.js/demo/) where I feebly attempt to show how it works (hosted on github pages; seems to load slowly some times).

The benefits I've observed in using breakpoints.js are 1) all breakpoints defined cleanly in one place, 2) styles grouped into modifier classes (this is nice for design, development, testing), 3) allows any kind of javascript logic to be executed when entering or exiting a breakpoint.

Both 1 and 2 could be accomplished with `@include` and element queries. And we'd still be on our own for 3.

**Comment by eeeps** [comment]
Per the back-and-forth with @keithjgrant in the kick-off: I'm gonna take these and a bunch of other links that I’ve ferreted away in my Pinboard over the years, and try to assemble a first draft of a “get-up-to-speed” summary/further reading page, for the wiki.

(And then close this.)

**Comment by eeeps** [comment]
Dumped everything in here into https://github.com/WICG/cq-usecases/wiki/Raw-informative-link-list for now; closing.
