### ISSUE TITLE
need kickoff meeting

### ISSUE THREAD

**Issue by tantek** [WICG/cq-usecases#50]
per @marcoscaceres comment in #44

**Comment by tomhodgins** [comment]
I am located in Toronto and available for a meeting any time, any day.

Please add me to Google hangouts and/or Skype:

gmail ☛ tomhodgins@gmail.com
skype ☛ innovati

I know we have some europeans on the team, so a time that's early in the day for me in Toronto would ensure it's not already too late in the day for the europeans!

**Comment by marcoscaceres** [comment]
I'm available from 8am (Melbourne time - GMT+10), except on Thursdays (your Wednesday). Again, it's not super critical that I join, but happy to make an effort. 

I'm marcos@marcosc.com on the Hangouts and "marcoscaceres" on the Skypes.

**Comment by djlotus** [comment]
I am just outside of Washington DC. i can be available anytime after 5pm EST (GMT -5)
GMAIL: lotusdj1
I can aquire Skype is needed.

**Comment by ZeeCoder** [comment]
Shouldn't we do this over the weekend? Saturday / Sunday?
Then we all might be able to make it.
I'm sort of in-between in London: GMT+0.

Someone would either have to get up quite early, or stay up quite late as far as I can tell. 😓

**Comment by djlotus** [comment]
Indeed @ZeeCoder. Weekend is most likely best for me. Can be available anytime.

**Comment by djlotus** [comment]
I can only judge by who has posted here but it looks like 5:00 PM any Saturday would work well. Would be 9:00 AM in Melbourne (coffee time) and 10:00 PM in London. 
when should we shoot for? The sooner the better.

**Comment by ZeeCoder** [comment]
That's perfectly fine for me. 👍

**Comment by beep** [comment]
Ach, the earliest Saturday I could do is 17 Feb. And while I think waiting a few weeks is fine—we’re not under a hard deadline here—if a weekday opened up in the interim, that’d be great for me.

**Comment by beep** [comment]
Heck, I just tossed together a quick poll of 5pm weekday meetings:

https://doodle.com/poll/9gc58ythnvwswanf

If folks could choose the ones that work for them, maybe we’ll get a quorum going?

**Comment by ZeeCoder** [comment]
Done with the vote 👍

**Comment by ZeeCoder** [comment]
Note that even though I'm leaning more towards doing this over the weekend, I would be probably fine with most weekdays too.
Would the kickoff be between the 6 participants of this issue?

**Comment by marcoscaceres** [comment]
Unfortunately, I can't do this weekend, but next week mostly works. Added to the poll.

**Comment by ZeeCoder** [comment]
The 5th or 6th looks like the best for me so far.
I would land with my plane just around the start of the meeting on the 5th, so that one is a bit dodgy for me.
I think I could only join 30-40 minutes late, if I'd make it at all. :/

**Comment by keithjgrant** [comment]
Added my votes

**Comment by beep** [comment]
@keithjgrant Thanks!

And thanks to everyone else who’s responded. We’ve got a couple strong candidates so far, but I’ll leave the poll open a couple more days—say, until 1 Feb—in case anyone else wants to vote.

**Comment by beep** [comment]
Hey folks! We’re going to have our kickoff call next week, on **6 February at 5pm (GMT-5 / NYC)**.

If you’re able to come, please add your preferred Hangouts account to this thread, if you haven’t already. I’ll send out invitations right before the call.

Thanks, folks! Excited to have our Actual Kick-off Meeting™ with you!

**Comment by eeeps** [comment]
eric.portis@gmail.com

**Comment by keithjgrant** [comment]
keithjgrant [at] gmail.com (hangouts only. Email is me [at] keithjgrant.com)

**Comment by ZeeCoder** [comment]
rpgmorpheus@gmail.com

**Comment by jpamental** [comment]
jason@rwt.io

**Comment by marcoscaceres** [comment]
mcaceres@mozilla.com

**Comment by maryroseMXXXVI** [comment]
Where I iving in different country I'm from the Philippines j

**Comment by maryroseMXXXVI** [comment]
Do you have a spare charger I need it

**Comment by ZeeCoder** [comment]
I'm just grabbing a quick bite and I'll be available.

**Comment by ZeeCoder** [comment]
@beep Is it now or an hour later?

**Comment by beep** [comment]
@zeecoder It’s at 5pm tonight, NYC time. So a little under 10 hours, I think?

**Comment by ZeeCoder** [comment]
aaaah I thought GMT, not GMT-5.

**Comment by hereinthehive** [comment]
Based on another thread looking for editors, I’ve been in touch with @tomhodgins and happy to join in tonight, if that’s cool

Skype: hereinthehive
Hangout: dan@hereinthehive.com or lookingintothesun@gmail.com

Is there an agenda for this meet-up?

**Comment by tantek** [comment]
@beep: "tantek" on that google hosted email thingie (only for Hangouts - not email :)
@marcoscaceres shall we use the #wicg IRC on irc.w3.org? (minutes, logging, queuing etc.)

**Comment by beep** [comment]
Invitations going out now! If you didn’t get one, please feel free to jump into 

https://hangouts.google.com/hangouts/_/ethanmarcotte.com/cq-kickoff

in a few minutes. We’ll be starting at the top of the hour. See you folks sooooooooon i’m so excited

**Comment by tantek** [comment]
A few of us (@tomhodgins @marcoscaceres at least) are in irc://irc.w3.org/wicg for chat backchannel (logged)

**Comment by marcoscaceres** [comment]
In the rush, I took minutes in different channel... will post them soon. Just cleaning them up.

**Comment by ZeeCoder** [comment]
wait so are we using slack or this irc? what's the difference?

**Comment by ZeeCoder** [comment]
I went straight to Slack after 🤔

**Comment by marcoscaceres** [comment]
[Draft Minutes are now available](https://github.com/WICG/cq-usecases/wiki/Minutes---Tuesday,-6-February-2018) - please feel free to correct any typos or things I recorded incorrectly or don't want attributed to you (I'm definitely not the best at taking minutes, so please check 'em!).

Also, please feel free to Tweet these out to let interested people know we've started the work! 🎉 As I said in the meeting (which I now realize I didn't actually include in the minutes), we all need to work keep the community informed. 

@ZeeCoder, we have a bot on IRC that handles creating minutes for us and creates a private record of discussions... so, it's a tool we sometimes use sometimes. 

I don't expect us to have too many calls (maybe one ever few months), unless folks feel it's helpful.

Again, it was great to virtually meet you all! Hope we have the opportunity over the next year to meet in person at conferences or if passing through each other's cities/towns. 

@eeeps or @beep - I think this can now be closed!

**Comment by beep** [comment]
@marcoscaceres The minutes look excellent to me. Thanks so much for taking them, and for helping us get to this point.

Everyone else: thanks so much for joining us yesterday! I’m really, really excited to be working on this with all of you.

> @eeeps or @beep - I think this can now be closed!

Consider this kickoff: HELD
