### ISSUE TITLE
List slack channel in README.md

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/cq-usecases#55]
Be great to list the newly minted slack channel in the README and possibly in the CONTRIBUTING.md file... the same applies to the other repo.

**Comment by ZeeCoder** [comment]
Yeah, I might do this tomorrow unless someone is faster :)

**Comment by beep** [comment]
@ZeeCoder Just checking: has this been resolved?

**Comment by ZeeCoder** [comment]
Almost there https://github.com/WICG/cq-usecases/pull/62
